pipeline {
    agent any

    environment {
        APP_NAME = "ecom-manish"
        CONTAINER_NAME = "ecom-manish"
        HOST_PORT = "4050"
        CONTAINER_PORT = "4050"
        NETWORK = "infra_default"
        ENV_FILE = "/var/lib/jenkins/workspace/env-files/.env-ecom-manish"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $APP_NAME:latest .
                '''
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker stop $CONTAINER_NAME || true
                docker rm $CONTAINER_NAME || true
                '''
            }
        }

        stage('Run New Container') {
            steps {
                sh '''
                docker run -d \
                  --name $CONTAINER_NAME \
                  --network $NETWORK \
                  --env-file $ENV_FILE \
                  -p $HOST_PORT:$CONTAINER_PORT \
                  --restart unless-stopped \
                  $APP_NAME:latest
                '''
            }
        }

        stage('Health Check') {
    steps {
        sh '''
        sleep 10
        curl --fail http://localhost:$HOST_PORT/health
        '''
    }
}
    }
}
